version: '3'

services:
  nginx:
    ports:
      - 5000:80
      
  tsnode-docker:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./src:/app/src:ro
    environment:
        PORT: 5000
        ORIGIN: "http://localhost:3000"
        COOKIE_SECRET: "secret"
        NODE_ENV: "development"
        MONGO_IP: mongo
        MONGO_PORT: 27017
        MONGO_USER: admin
        MONGO_PASS: 1234
        REDIS_IP: redis
        REDIS_PORT: 6379
        REDIS_PASS: 1234
        SECRET_SESSION: 'secret'
    command: npm run dev

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    depends_on:
      - mongo

      