version: '1.0'

services:
  tsnode-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: tsnode-docker
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev