version: '3'

services:
  tsnode-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src:ro
    expose:
      - '5000'
    ports:
      - '5000:5000'
