version: '3'

services:
  tsnode-docker:
    build:
      args:
        NODE_ENV: development
    environment:
        PORT: 5000
        ORIGIN: "http://localhost:3000"
        COOKIE_SECRET: "secret"
        NODE_ENV: "development"
    container_name: development
    command: npm run dev