version: '3'

services:
  tsnode-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '5000'
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:

