version: '3'

services:
  tsnode-docker:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./src:/app/src:ro
    environment:
        PORT: 5000
        ORIGIN: "http://localhost:3000"
        COOKIE_SECRET: "secret"
        NODE_ENV: "development"
        MONGO_IP: mongo
        MONGO_PORT: 27017
        MONGO_USER: admin
        MONGO_PASS: 1234
    container_name: development
    command: npm run dev

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234