version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 5000:80
    volumes:
      - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  tsnode-docker:
    image: andrewmoquia/tsnode-docker
    build:
      context: . 
      dockerfile: Dockerfile
      target: base
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./environment/redis:/data

volumes:
  mongo-db:

